### ISSUE TITLE
我无缘无故被CNBlackListR误封了，请你帮忙，谢谢。

### ISSUE THREAD

**Issue by zhuwenjie2346** [CNBlackListR/white-book#11]
大神你在不在，能不能帮我个忙，谢谢！
我在TG上被@CNBlackListR在今年9月份时莫名奇妙的误封了，Bot解封不能用，这个误封导致我想加别的TG(群里有这个机器人并启用了自动踢人)的正规群加不了。受到一定的影响。希望你帮我解封一下！不甚感激！！
起因是我发了一个youtube网站上的的正规视频的链接就被这个机器人封了
请你帮帮忙！谢谢！
我的TG用户名是@zhuwenjie2346，谢谢，它误封我后导致我加其他含这个机器人的群都加不了，谢谢！请你帮我解封一下，谢谢！

**Comment by NeverBehave** [comment]
Locked and Blocked due to wrong issue format.
