### ISSUE TITLE
请不要罔顾事实避重就轻

### ISSUE THREAD

**Issue by coldjelly** [CNBlackListR/white-book#20]
CNBlackListR机器人丧失信任的重点不在于有人传播“网信办”之类的话，而是机器人暗地里删除一些政治言论和批评CNBLR机器人的言论，还把发表了这些话的人全部永封。因为发广告被封的你们把昵称和消息内容都公开了，因为其它原因被封的却是私下操作。对后者，你们虚与委蛇，一会说查不到就说明没被封，一会说是算法不完美误封。说是算法误封的时候，你们又能查到记录了，又能从私人频道调取被封的消息内容了。CNBLR的[隐私策略](https://github.com/CNBlackListR/white-book/blob/master/%E9%A1%B9%E7%9B%AE%E8%A7%84%E8%8C%83/%E9%9A%90%E7%A7%81%E7%AD%96%E7%95%A5.md)居然还公示“我们不会以任何方式存储您的聊天记录数据”。

![](https://imgur.com/JrPg53E.jpg)
![](https://imgur.com/bMRn9vd.jpg)
![](https://imgur.com/xAxSqT0.jpg)

你们凭自己喜好随意给机器人添加删封规则，大量用户被封后，却不解封。好不容易找到了你们的[Telegram交流群](https://t.me/CNBlackListRChat)，则是名义上在这申诉，实际上没几个人能申诉成功，还要被你们嘲讽羞辱一番。等用户自己把截图发出来了，把事情写成文章了，你们再把这些消息和文章又添加进封禁规则里，谁敢说CBLR的负面消息谁就被封号。上图的这位用户因为转发批评你们的文章被封，求了半天你们解封了，还要说他是昵称含广告才被封。

![](https://i.imgur.com/ZFFd2BL.jpg)
![](https://imgur.com/jKcA5hi.jpg)

从2017年9月CNBLR机器人的前身CBL逼迫《药丸时报》频道解散到现在，你们干了这么多好事，受到舆论抨击，不想想自己有啥问题，却先声称是别人“大放黑屁”，后又把责任推给zh_groups、TGCN、Telegram官方、ADNK算法……你们的话有可信度吗？批评CNBLR瞬间被封是因为昵称含广告？是因为群管理员秒封？是因为被其他用户举报TG官方秒封？出一次事情别人还能信你，一而再再而三删除消息封禁用户又不解封，把Telegram中文用户都当傻子耍？CBLR丧失用户信任难道不是因为你们到处肆意封号，而是有人恶意造谣中伤你们？也不想想不信任CBLR的民意基础怎么来的？CNBlackListR的某几位维护人员到现在还在追查所谓的此次事件幕后黑手，对抨击你们的人加以人身威胁，甚至去年还人肉搜索了CNBlackListR的批评者。

为什么批评CBLR会被暗地封禁，为什么批评jvbao也会被封，为什么讨论翻墙工具还可能被封，为什么想成功申诉解封十分困难，为什么CBLR开发者不承认封号的事实，刚刚发表的[“反思与新思路”](https://github.com/CNBlackListR/white-book/blob/master/%E5%85%AC%E5%BC%80%E8%AF%B4%E6%98%8E/%E5%8F%8D%E6%80%9D%E4%B8%8E%E6%96%B0%E6%80%9D%E8%B7%AF.md)还是一个字都没提。通篇下来没有任何实质内容。

![](https://i.imgur.com/Vi3cpTQ.jpg)

你们宣称你们反对[jvbao](https://twitter.com/jvbaoillegal)，可任何人谈论jvbao都要被CBLR机器人封禁，被你们“误封”的人你们也拒不解封。假设存在一个jvbao的粉丝团体，他们搞了一个机器人，会封禁所有对jvbao不利的消息，同时以一个反spam机器人的形象作为伪装。那么试问CBLR和这种团体有何区别？听说过有个词叫做口嫌体正直吗？

以CNBLR工作者的工作态度来看，大概确实跟官方政府机构没什么关系，而是自备干粮的。网信办在墙内审查言论，CNBLR在墙外审查言论；强力机构在墙内镇压异议者，CNBLR在墙外使用流氓手段打击批评者，两者干的事如出一辙。CNBLR被指责行径如同网信办，不是很正常吗？

**Comment by NeverBehave** [comment]
“如同”和“就是”是两回事，不过你说的对

有一段时间广告/垃圾消息太多，在大部分操作自动化以后按照关键词误封率增加很多
ANBK方面接管CNBL确实没有放出消息，因为有工作室针对性的开发机器人对抗我们的广告规则（观察封禁列表和消息），也有专门来发申诉消息测试我们解封规范的。说实话没有志愿者再经过那段时间的消息轰炸以后还可以对每个请求好声好气的解释和分析。团队内部的偏激想法也没有即时解决。所以，拒不解封的问题也只能我在这里说抱歉。我希望我们放弃中心化管理的机器人方案可以缓解人造成的问题

此外就是，我也是最近才开始回归这部分事务，这部分事情我了解的确实不多。信任危机我希望可以直接通过改变现有执行方式来表现改变的决心
毕竟人无完人，如果确实到最后不能挽回，我倒是希望可以有完善成熟的方案来替代当前的广告过滤方案。毕竟关闭现在的CNBLR然后换到一个新的牌子来解决信任问题的方式……有点掩耳盗铃

**Comment by HiedaNaKan** [comment]
![Screenshot_20190425-164916_Telegram_X](https://user-images.githubusercontent.com/31186920/56723313-46ebaf00-677b-11e9-92ae-2eb872687325.png)

**Comment by HairProtection** [comment]
**关闭现在的CNBLR然后换到一个新的牌子**还是有一点用的。之前把CBL改名为CNBlackListR不就确实起到了一点作用么？被“误封”的人请求解封不需要**好声好气的解释和分析**，从来都是请求的人才需要解释吧？这么久了，有时间开嘲讽，有时间建Telegram Channel出道别人，没时间解封？

楼上发的图挺有意思。前几天有人因为anti-jvbao被封的时候，这位和他的小伙伴们说的可是因为”群发“才被封。屏蔽jvbao的事为什么不敢公开反倒欺骗他人？如果图中所述属实，聊天记录是4月17日的，为什么早就认识到了问题，还是不去解决目前仍然这样封禁无辜用户？既然已经认识到被封的是anti-jvbao，还**拒不解封**，那不**就是**在帮jvbao的忙么？

况且封jvbao则证明了CNBLR项目中所述的封禁标准纯属一纸空文。这与jvbao是什么人干了什么事没有关系。运维人员是凭个人喜好修改封禁规则的，而且不透明。再把批评CNBLR的言论也加入封禁规则就不奇怪了。

**Comment by NeverBehave** [comment]
1. CNBL和CNBLR完全是两个团队，之前的作者因为像这样的事情直接选择退出了。
2. 出道的证据是什么？上次类似的事件是一年前，而且我们做过声明并清理了相关的管理人员。
3. 没有及时处理的问题我已经说过了：自动化后日志几乎没有人复查，当时的方针是按照群主和我们收集到的广告样本优先进行处理，包括现在也是。所以我们在计划撤除中心化管理
4. 我们本身也有不受欢迎的人员判定，这个标准**确实有被滥用的问题**，但是是**在规则内，且已经声明过**。这个问题也是我们当时推行全自动化的动力之一。然而事实证明这并不是一个好的选择，尤其是还是要人工介入的情况下
5. 批评的言论加入封禁规则的问题是当事人之前被判定过广告/滥用但是解封申诉失败，后面使用同个账号发消息时被无差别处理的。这可以算是断章取义吗？

认识到和能做到是两回事。如果您能做个替代品也是很🐒的。我们早就说过很欢迎类似的机器人或者项目，如果能做到更好的效果的话：到后面大家都是在指责做的不好的地方而没人真正的来贡献。我觉得对于任何一个项目都是毁灭性的打击。因为确实这类项目这个度都不好把控

这个事情到这里，如果看官仍然有疑问，很简单：**推荐别用**。没错，官方推荐别用。我们还是会在这里，我们也说明了我们自己的方向，我们也需要时间成长。**TG也是个自由的地方，你可以选择。**我们没有任何强迫选择的地方。如果一个群用了，也许是群组和管理员确实没有找到更好的方案，你如果有更好的不妨和他们推荐一下。

让我们看看下一位勇士做的如何？

--EOT--
_请管理员或其他人员不用继续**站在官方**与此Issue发表言论：谢谢好意，说到底舆论有理，然而争论并不能带来实质的改变。**如果可以，请给我们的[新开放计划](https://github.com/CNBlackListR/white-book/issues/19)做贡献**。新开的其他相关issue将会被关闭。_
