### ISSUE TITLE
我的账号被封禁了，申诉bot打不开

### ISSUE THREAD

**Issue by 99junlin99** [CNBlackListR/white-book#4]
我是界面下，不知道为啥弹出一个按钮，点了之后被封禁，感觉是被劫持了（我自动发了伊斯兰文好像。。）bot，我start之后，一直让我验证，我输入了正群的答案甄龙友也不行 id是@Junlin_09

**Comment by LC-CYAN** [comment]
我也想知道莫名被清真怎么办

**Comment by NeverBehave** [comment]
请提供以下id谢谢，稍后会有答复

**Comment by 99junlin99** [comment]
昨天被解封了，谢谢
