### ISSUE TITLE
你好 我的id莫名被封禁了 bot无法完成验证无法申诉

### ISSUE THREAD

**Issue by mrzenwell** [CNBlackListR/white-book#6]
今天在koolshare群内准备发言，但输入框莫名变成一堆看不懂的字符，按了一下自动发出一段类似清真文字的消息，然后就被秒封了，而且是一下被好几个群封了😂这该怎么办啊！
我的id是Booui 昵称小 啦啦 求助！
![screenshot_20180831-145453_telegram](https://user-images.githubusercontent.com/28263140/44916360-22644200-ad68-11e8-87f8-87437c4425ae.jpg)
![screenshot_20180831-215245_telegram](https://user-images.githubusercontent.com/28263140/44916402-3b6cf300-ad68-11e8-9e1b-2fab31eb2111.jpg)

**Comment by NeverBehave** [comment]
已经解封

**Comment by zhuwenjie2346** [comment]
管理员大大帮帮忙，我因为发了一个youtube正规链接就突然被这个机器人封了，跟机器人@CNBlacklistRAppeal申请解封还解封不了，请你帮给我解封一下，不甚感激！谢谢！我的tg用户名是 @zhuwenjie2346   ,谢谢！tg的id是225098921，谢谢！
